[build]
  command = "pip install -r requirements.txt && python your_build_script.py"  # replace with your real build command
  publish = "public"  # change this to your actual output folder if different

[build.environment]
  PYTHON_VERSION = "3.10"
  PIP_NO_CACHE_DIR = "true"
  GIT_DEPTH = "0"  # ensures full Git clone just in case skl2onnx or others need it
